### Importando librerías Numpy

In [94]:
import numpy as np

##### Creando una lista de 10 elementos

In [95]:
lista =  list(range(1,11))
lista_1 = [1,2,3,4,5,6,7,8,9,10]
lista
lista_1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

#### Transformando la Lista a un Array

In [96]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Comprobando el tipo de objeto

In [97]:
type(arreglo)

numpy.ndarray

#### Corroborando el tipo de datos del arreglo

In [98]:
arreglo.dtype

dtype('int32')

#### Definiendo el Array de int32 a float32

In [99]:
np.array(arreglo, dtype = np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

#### Sigue siendo un array de int32 (Solo se definió, no se transformó)

In [100]:
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Transformando los datos de int32 a float32

In [101]:
arreglo.astype(np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

#### Para sacar el promedio

In [102]:
promedio = np.mean(arreglo)

#### Para sacar la mediana

In [103]:
mediana = np.median(arreglo)

#### Desviación estandar del arreglo

In [104]:
desviacion_sta = np.std(arreglo)

arreglonuevo = np.arange(1,11)
arreglonuevo

In [105]:
arreglonuevo2 = np.arange(1,11)
arreglonuevo2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

<h3 style = "color:blue"> <b>Algunas funciones de numpy</b></h3>
<h4 style ="color:aquamarine"> Obteniendo el promedio del array no olvidar  </h4>

In [106]:
promedio = np.mean(arreglo)
promedio

5.5

### Desviación estandar del Arreglo

In [107]:
desviacion_sta = np.std(arreglo)
desviacion_sta

2.8722813232690143

#### Generación de uin arreglo de 10 elementos de solo "unos"

In [108]:
arreglo_de_unos = np.ones(10)
arreglo_de_unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Transformandolo a int

In [109]:
arreglo_int_ones = arreglo_de_unos.astype(int)
arreglo_int_ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Generación de un arreglo de ceros 5

In [110]:
arreglo_de_ceros = np.zeros(5)
arreglo_de_ceros

array([0., 0., 0., 0., 0.])

### Utilizando la funcion random
#### agregando un arreglo aleatorio de 5 elementos

In [111]:
arreglo_aleatorio = np.random.rand(3)
arreglo_aleatorio

array([0.97828522, 0.38152549, 0.33232861])

##### Generando una matriz aleatoria de 3x3 (una matriz es una anidación de arreglos)

In [112]:
matriz = np.random.rand(3,3)
matriz

array([[0.85661053, 0.10073308, 0.06205183],
       [0.96855577, 0.13690002, 0.91025092],
       [0.9055393 , 0.83368083, 0.54441969]])

### Generando una matriz aleatoria de 10 numeros enteros de numeros del 1 al 100 (Partimos desde el 1 hasta el 100 y matriz cuadrada 10(filas horizontales)x10(columnas verticales))

In [113]:
matriz2 = np.random.randint(1,100,(10,10))
matriz2

array([[42, 36, 61, 75, 36, 42, 64, 53, 81, 54],
       [74, 94, 21, 45, 80, 16, 41,  4, 65, 38],
       [27,  6,  8, 34, 79,  1, 43, 65, 30, 84],
       [98, 96, 25, 37, 51, 49, 60, 83, 58, 79],
       [90, 32, 37, 58, 33, 30, 35, 19, 32,  6],
       [96, 22, 60, 24, 31, 73,  4, 55, 76, 18],
       [68, 66, 87, 99, 89, 32, 42, 13, 84, 16],
       [97, 16, 16, 43, 38, 59, 91,  3, 60,  5],
       [35, 96, 26, 89, 94, 13, 92, 50, 93, 77],
       [57,  3, 39, 54,  5, 98, 46, 85, 11, 98]])

### Generando un arreglo aleatorio de 10 números enteros del 1 al 5

In [114]:
arreglo_aleatorio2 = np.random.randint(1,10,100)
arreglo_aleatorio2

array([8, 2, 3, 4, 8, 5, 2, 2, 7, 7, 5, 6, 4, 5, 8, 9, 8, 6, 6, 5, 8, 3,
       7, 8, 3, 4, 9, 3, 7, 7, 3, 2, 3, 4, 4, 2, 8, 5, 1, 3, 4, 4, 5, 8,
       5, 5, 9, 1, 7, 9, 1, 8, 9, 4, 8, 7, 8, 9, 9, 6, 7, 5, 8, 9, 7, 1,
       7, 1, 4, 7, 4, 3, 5, 5, 9, 1, 3, 6, 6, 1, 4, 6, 5, 1, 6, 5, 3, 5,
       2, 5, 8, 7, 5, 3, 5, 3, 6, 8, 9, 5])